### PR TITLE
enhanced automation

### PR DESCRIPTION
**Pull request by NickDrew**
Hi Atul

Nice project! I thought I would contribute to it by adding some of the lazy-dev automation scripts I use in modular projects.

I have added:

- A package at the top level that allows a single-command setup of the api/web/mobile sub-packages without having to change directories.

- The concurrently module to this top level package, which allows a single-command dev run of the api/web packages without having to change directories. A child process will be spawned for both api and web. Their stdout & stderr will be sent to this single console, with a prefix to indicate the source. If either processes fails both will be killed.

I have updated the readme file appropriately.

### CODE REVIEW

**Comment by atulmy** [comment]
@NickDrew thanks for the PR. I'm wondering if understanding this additional configuration/automation may create some confusion for lesser experienced developers? What do you think?

**Comment by NickDrew** [comment]
@atulmy  That's a fair point.

As I understand it this project is also for intermediate developers looking to explore simple implementations of advanced concepts?

To support both I could leave in the original readme commands as they were, then append the optional automation commands towards the bottom?

**Comment by atulmy** [comment]
> To support both I could leave in the original readme commands as they were, then append the optional automation commands towards the bottom?

That would be better. Keeping the existing workflow as is and adding additional automation would work.

**Comment by NickDrew** [comment]
Changes made as requested.

**Comment by NickDrew** [comment]
Changes made as requested.

**Comment by atulmy** [comment]
Great! Thanks for the contribution @NickDrew! 🎉

**Pull request merged**
